// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParcelDelivery.Api.Data;

#nullable disable

namespace ParcelDelivery.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260215080627_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParcelDelivery.Api.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ParcelDelivery.Api.Models.Order", b =>
                {
                    b.OwnsMany("ParcelDelivery.Api.Models.Parcel", "Parcels", b1 =>
                        {
                            b1.Property<Guid>("OrderId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<int>("Content");

                            b1.Property<Guid>("Id");

                            b1.Property<decimal>("Value");

                            b1.Property<double>("Weight");

                            b1.HasKey("OrderId", "__synthesizedOrdinal");

                            b1.ToTable("Orders");

                            b1
                                .ToJson("Parcels")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("ParcelDelivery.Api.Models.Recipient", "Recipient", b2 =>
                                {
                                    b2.Property<Guid>("ParcelOrderId");

                                    b2.Property<int>("Parcel__synthesizedOrdinal");

                                    b2.Property<Guid>("Id");

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.Property<string>("Phone")
                                        .IsRequired();

                                    b2.HasKey("ParcelOrderId", "Parcel__synthesizedOrdinal");

                                    b2.ToTable("Orders");

                                    b2.WithOwner()
                                        .HasForeignKey("ParcelOrderId", "Parcel__synthesizedOrdinal");

                                    b2.OwnsOne("ParcelDelivery.Api.Models.Address", "Address", b3 =>
                                        {
                                            b3.Property<Guid>("RecipientParcelOrderId");

                                            b3.Property<int>("RecipientParcel__synthesizedOrdinal");

                                            b3.Property<string>("CustomAddressType");

                                            b3.Property<string>("HouseNo")
                                                .IsRequired();

                                            b3.Property<Guid>("Id");

                                            b3.Property<string>("Street")
                                                .IsRequired();

                                            b3.Property<int>("Type");

                                            b3.HasKey("RecipientParcelOrderId", "RecipientParcel__synthesizedOrdinal");

                                            b3.ToTable("Orders");

                                            b3.WithOwner()
                                                .HasForeignKey("RecipientParcelOrderId", "RecipientParcel__synthesizedOrdinal");

                                            b3.OwnsOne("ParcelDelivery.Api.Models.City", "City", b4 =>
                                                {
                                                    b4.Property<Guid>("AddressRecipientParcelOrderId");

                                                    b4.Property<int>("AddressRecipientParcel__synthesizedOrdinal");

                                                    b4.Property<string>("Code")
                                                        .IsRequired();

                                                    b4.Property<string>("Name")
                                                        .IsRequired();

                                                    b4.Property<int>("Pincode");

                                                    b4.HasKey("AddressRecipientParcelOrderId", "AddressRecipientParcel__synthesizedOrdinal");

                                                    b4.ToTable("Orders");

                                                    b4.WithOwner()
                                                        .HasForeignKey("AddressRecipientParcelOrderId", "AddressRecipientParcel__synthesizedOrdinal");
                                                });

                                            b3.Navigation("City")
                                                .IsRequired();
                                        });

                                    b2.Navigation("Address")
                                        .IsRequired();
                                });

                            b1.Navigation("Recipient")
                                .IsRequired();
                        });

                    b.Navigation("Parcels");
                });
#pragma warning restore 612, 618
        }
    }
}
